CREATE TABLE blogful_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullname TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    password TEXT,
    nickname TEXT,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- articles table must be altered to add the Foreign Key column for reference relationship
ALTER TABLE blogful_articles
    ADD COLUMN
        author INTEGER REFERENCES blogful_users(id)
        ON DELETE SET NULL;
