CREATE TABLE blogful_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    date_commented TIMESTAMPTZ DEFAULT now() NOT NULL,

    article_id INTEGER 
        REFERENCES blogful_articles(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER 
        REFERENCES blogful_users(id) ON DELETE CASCADE NOT NULL
);

-- If the article record is deleted,
-- the comments made on that article will also be deleted.
-- If the user/author is deleted,
-- all the comments made by that author will be deleted.